"""
sparse_query_expander.py

Enriches queries by combining original tokens with semantically similar terms retrieved from a precomputed Word2Vec expansion dictionary.

Workflow:
  1. Initializes a SimpleQueryAnalyzer to clean text (removes URLs, mentions, hashtags).
  2. Loads a Word2Vec lookup table (generated by word2vec_expansion.py).
  3. Iterates through input queries, tokenizing the original text.
  4. Expands the token set by looking up synonyms that meet the similarity threshold.
  5. Merges unique terms into a single "sparse" field for indexing/retrieval.

Parameters (Command Line):
  threshold (argv[1])  Minimum cosine similarity score to include a term (default: 0.9).
  max_terms (argv[2])  Maximum number of expansion terms per original token (default: 10).

Input/Output:
  - input_path:   JSON containing original queries and existing metadata.
  - model_path:   The word2vec_expansion.json lookup dictionary.
  - output_path:  JSON enriched with the "sparse" expansion string.

Usage:
  python sparse_query_expander.py [threshold] [max_terms]
"""

import json
import re
import sys
import nltk
from tqdm import tqdm
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords

# Minimum NLTK resources
nltk.download('punkt', quiet=True)

class SimpleQueryAnalyzer:
    def __init__(self, stopwords_file):
        # Cleanup patterns (URL, @mentions, # symbol)
        self.url_pattern = re.compile(r"https?://\S+\s?")
        self.mention_pattern = re.compile(r"@\w+\s?")
        self.hashtag_symbol = re.compile(r"#")

        # Loading custom stopwords
        try:
            with open(stopwords_file, 'r', encoding='utf-8') as f:
                self.stop_words = set(line.strip().lower() for line in f if line.strip())
        except FileNotFoundError:
            self.stop_words = set(stopwords.words('english'))

        # Tokenizer: alphanumerical and dashes
        self.tokenizer = RegexpTokenizer(r"[a-z0-9\-]+")

    def analyze(self, text):
        if not text:
            return []

        # 1. String cleanup
        text = self.url_pattern.sub("", text)
        text = self.mention_pattern.sub("", text)
        text = self.hashtag_symbol.sub("", text)

        # 2. Lowercase and Tokenization
        text = text.lower()
        tokens = self.tokenizer.tokenize(text)

        # 3. Stopwords removal (NO stemming)
        return [t for t in tokens if t not in self.stop_words]

def run_expansion_pipeline(input_path, model_path, output_path, stop_path, threshold, max_terms):
    analyzer = SimpleQueryAnalyzer(stop_path)

    print("Loading resources...")
    with open(model_path, 'r', encoding='utf-8') as f:
        expansion_lookup = json.load(f)

    with open(input_path, 'r', encoding='utf-8') as f:
        queries = json.load(f)

    final_results = []

    for q in tqdm(queries, desc="Processing"):
        original_text = q.get('original', '')

        original_tokens = analyzer.analyze(original_text)
        combined_terms = set(original_tokens)

        # Adding terms from Word2Vec
        for token in original_tokens:
            if token in expansion_lookup:
                similars = [item['term'] for item in expansion_lookup[token][:max_terms]
                            if item['score'] >= threshold]
                combined_terms.update(similars)

        # Building JSON
        output_obj = {
            "index": q.get("index"),
            "original": original_text,
            "expanded": q.get("expanded", ""),
            "sparse": " ".join(list(combined_terms)),
            "pubkey": q.get("pubkey")
        }

        final_results.append(output_obj)

    print(f"Saving in {output_path}...")
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(final_results, f, indent=2)

if __name__ == "__main__":
    # Command line parameters (Threshold e Max Terms)
    THRESHOLD = float(sys.argv[1]) if len(sys.argv) > 1 else 0.9
    MAX_TERMS = int(sys.argv[2]) if len(sys.argv) > 2 else 10

    run_expansion_pipeline(
        input_path='../../../../../../data/expanded_queries_bge_large.json',
        model_path='word2vec_expansion.json',
        output_path='../../../../../../data/expanded_queries_en.json',
        stop_path='../../../../../../data/stoplist_en_TEX.txt',
        threshold=THRESHOLD,
        max_terms=MAX_TERMS
    )