#!/usr/bin/env python3
"""
Generate comparison plots and non-parametric statistics from
unipd.se.StatisticalEvaluator JSON files.

The script complements anova_tukey_boxplot.py. It keeps the per-query
distribution plots, then adds:

1. mean score plots with 95% confidence intervals
2. baseline delta plots with 95% confidence intervals
3. Friedman omnibus tests across systems
4. pairwise Wilcoxon signed-rank tests with Holm correction
5. per-metric Holm-adjusted p-value heatmaps
6. an overview heatmap of mean metric values

Example:
    python3 code/py/statistical_comparison_plots.py \
      --inputs \
        results/statistics/nemotron_top100_baseline_en_dev.json \
        results/statistics/nemotron_top1000_baseline_en_dev.json \
        results/statistics/nemotron_lora_top1000_en_dev.json \
      --all-metrics \
      --outdir results/statistics/en_dev_comparison \
      --title "English DEV"
"""

from __future__ import annotations

import argparse
import csv
from itertools import combinations
import math
from pathlib import Path
import statistics
from typing import Any

from anova_tukey_boxplot import (
    ALL_METRICS,
    METRIC_CHOICES,
    METRIC_SPECS,
    load_rows,
    resolve_metric_name,
)


INSTALL_HINT = "python3 -m pip install pandas matplotlib scipy"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create plots and non-parametric statistical comparisons from "
            "StatisticalEvaluator JSON outputs."
        )
    )
    parser.add_argument(
        "--inputs",
        nargs="+",
        required=True,
        help="One or more JSON files generated by unipd.se.StatisticalEvaluator.",
    )
    parser.add_argument(
        "--metrics",
        nargs="+",
        choices=METRIC_CHOICES,
        default=["mrr5"],
        help="Metrics to plot. Use 'all' or --all-metrics for every supported metric.",
    )
    parser.add_argument(
        "--all-metrics",
        action="store_true",
        help="Generate plots and statistics for every supported metric.",
    )
    parser.add_argument(
        "--outdir",
        required=True,
        help="Directory where plots and CSV files will be written.",
    )
    parser.add_argument(
        "--title",
        default="System comparison",
        help="Title prefix used in generated plots.",
    )
    parser.add_argument(
        "--baseline",
        default=None,
        help=(
            "System name used for delta plots. If omitted, the first input "
            "system is used."
        ),
    )
    parser.add_argument(
        "--alpha",
        type=float,
        default=0.05,
        help="Significance level for confidence intervals and Holm decisions.",
    )
    return parser.parse_args()


def require_dependency(module_name: str) -> None:
    try:
        __import__(module_name)
    except ImportError as exc:
        raise SystemExit(
            f"Missing Python dependency '{module_name}'. Install it with:\n{INSTALL_HINT}"
        ) from exc


def selected_metrics(args: argparse.Namespace) -> list[str]:
    if args.all_metrics or "all" in args.metrics:
        return list(ALL_METRICS)

    metrics: list[str] = []
    for metric in args.metrics:
        canonical = resolve_metric_name(metric)
        if canonical not in metrics:
            metrics.append(canonical)
    return metrics


def confidence_interval(values: list[float], alpha: float) -> tuple[float, float]:
    from scipy import stats

    count = len(values)
    mean = statistics.fmean(values) if values else 0.0
    if count < 2:
        return mean, mean

    std_dev = statistics.stdev(values)
    critical = float(stats.t.ppf(1.0 - alpha / 2.0, count - 1))
    half_width = critical * std_dev / math.sqrt(count)
    return mean - half_width, mean + half_width


def load_metric_frame(input_paths: list[Path], metric_name: str) -> tuple[Any, list[str]]:
    import pandas as pd

    rows: list[dict] = []
    for input_path in input_paths:
        rows.extend(load_rows(input_path, metric_name))

    if not rows:
        raise SystemExit("No per-query rows were found in the provided JSON files.")

    df = pd.DataFrame(rows)
    duplicate_rows = df.duplicated(["qid", "system"])
    if duplicate_rows.any():
        sample = df.loc[duplicate_rows, ["qid", "system"]].head(5).to_dict("records")
        raise SystemExit(f"Duplicate qid/system rows found: {sample}")

    system_order = list(dict.fromkeys(df["system"].tolist()))
    pivot = df.pivot(index="qid", columns="system", values="score")
    pivot = pivot.reindex(columns=system_order)

    if pivot.isna().any().any():
        missing = []
        for system in system_order:
            missing_qids = pivot.index[pivot[system].isna()].tolist()
            if missing_qids:
                missing.append(f"{system}: {missing_qids[:5]}")
        raise SystemExit(
            "The selected runs do not share a complete qid set. Missing samples: "
            + "; ".join(missing)
        )

    return pivot.astype(float), system_order


def summarize_metric(
    pivot: Any,
    system_order: list[str],
    metric_name: str,
    alpha: float,
) -> list[dict]:
    rows = []
    for system in system_order:
        values = pivot[system].tolist()
        mean = statistics.fmean(values)
        ci_low, ci_high = confidence_interval(values, alpha)
        rows.append(
            {
                "metric": metric_name,
                "metric_label": METRIC_SPECS[metric_name].label,
                "system": system,
                "queries": len(values),
                "mean": mean,
                "median": statistics.median(values),
                "std_dev": statistics.stdev(values) if len(values) > 1 else 0.0,
                "ci_low": ci_low,
                "ci_high": ci_high,
                "min": min(values),
                "max": max(values),
            }
        )
    return rows


def friedman_test(pivot: Any, system_order: list[str], metric_name: str) -> dict:
    from scipy import stats

    if len(system_order) < 3:
        return {
            "metric": metric_name,
            "statistic": "",
            "p_value": "",
            "systems": len(system_order),
            "queries": len(pivot),
            "note": "Friedman test requires at least three systems.",
        }

    row_ranges = pivot[system_order].max(axis=1) - pivot[system_order].min(axis=1)
    if float(row_ranges.max()) == 0.0:
        return {
            "metric": metric_name,
            "statistic": 0.0,
            "p_value": 1.0,
            "systems": len(system_order),
            "queries": len(pivot),
            "note": "All systems have identical per-query scores.",
        }

    statistic, p_value = stats.friedmanchisquare(
        *[pivot[system].tolist() for system in system_order]
    )
    return {
        "metric": metric_name,
        "statistic": float(statistic),
        "p_value": float(p_value),
        "systems": len(system_order),
        "queries": len(pivot),
        "note": "",
    }


def holm_adjust(p_values: list[float]) -> list[float]:
    adjusted = [1.0] * len(p_values)
    previous = 0.0
    ordered = sorted(range(len(p_values)), key=lambda index: p_values[index])
    total = len(p_values)

    for rank, index in enumerate(ordered):
        multiplier = total - rank
        corrected = min(1.0, multiplier * p_values[index])
        previous = max(previous, corrected)
        adjusted[index] = previous

    return adjusted


def pairwise_wilcoxon(
    pivot: Any,
    system_order: list[str],
    metric_name: str,
    alpha: float,
) -> list[dict]:
    from scipy import stats

    rows = []
    raw_p_values = []
    for system_a, system_b in combinations(system_order, 2):
        values_a = pivot[system_a].tolist()
        values_b = pivot[system_b].tolist()
        diffs = [b - a for a, b in zip(values_a, values_b)]

        if all(diff == 0.0 for diff in diffs):
            statistic = 0.0
            p_value = 1.0
        else:
            statistic, p_value = stats.wilcoxon(
                values_b,
                values_a,
                zero_method="pratt",
                alternative="two-sided",
            )

        mean_diff = statistics.fmean(diffs)
        ci_low, ci_high = confidence_interval(diffs, alpha)
        rows.append(
            {
                "metric": metric_name,
                "group1": system_a,
                "group2": system_b,
                "mean_diff_group2_minus_group1": mean_diff,
                "median_diff_group2_minus_group1": statistics.median(diffs),
                "ci_low": ci_low,
                "ci_high": ci_high,
                "wins_group2": sum(1 for diff in diffs if diff > 0.0),
                "losses_group2": sum(1 for diff in diffs if diff < 0.0),
                "ties": sum(1 for diff in diffs if diff == 0.0),
                "wilcoxon_statistic": float(statistic),
                "p_value": float(p_value),
            }
        )
        raw_p_values.append(float(p_value))

    adjusted = holm_adjust(raw_p_values)
    for row, adjusted_p in zip(rows, adjusted):
        row["p_holm"] = adjusted_p
        row["reject_holm"] = adjusted_p < alpha

    return rows


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def plot_boxplot(
    pivot: Any,
    system_order: list[str],
    metric_label: str,
    title: str,
    out_png: Path,
) -> None:
    import matplotlib.pyplot as plt

    data = [pivot[system].tolist() for system in system_order]
    fig_width = max(9.0, 1.6 * len(system_order) + 3.0)
    fig, ax = plt.subplots(figsize=(fig_width, 7.0))
    ax.boxplot(
        data,
        patch_artist=True,
        widths=0.48,
        boxprops={"facecolor": "white", "edgecolor": "#3f3f3f", "linewidth": 1.3},
        whiskerprops={"color": "#3f3f3f", "linewidth": 1.2},
        capprops={"color": "#3f3f3f", "linewidth": 1.2},
        medianprops={"color": "#d95f02", "linewidth": 1.6},
        flierprops={
            "marker": "o",
            "markerfacecolor": "white",
            "markeredgecolor": "#2b2b2b",
            "markersize": 5,
            "linestyle": "none",
        },
    )
    ax.set_title(title, fontsize=16, pad=12)
    ax.set_ylabel(metric_label)
    ax.set_xticks(range(1, len(system_order) + 1))
    ax.set_xticklabels(system_order, rotation=20, ha="right")
    ax.set_ylim(-0.03, 1.03)
    ax.grid(axis="y", linestyle=":", linewidth=0.9, alpha=0.75)
    ax.set_axisbelow(True)
    fig.tight_layout()
    fig.savefig(out_png, dpi=200)
    plt.close(fig)


def plot_mean_ci(
    summary_rows: list[dict],
    metric_label: str,
    title: str,
    out_png: Path,
) -> None:
    import matplotlib.pyplot as plt

    systems = [row["system"] for row in summary_rows]
    means = [float(row["mean"]) for row in summary_rows]
    lower = [mean - float(row["ci_low"]) for mean, row in zip(means, summary_rows)]
    upper = [float(row["ci_high"]) - mean for mean, row in zip(means, summary_rows)]
    y_positions = list(range(len(systems)))

    fig_height = max(4.5, 0.52 * len(systems) + 2.0)
    fig, ax = plt.subplots(figsize=(9.5, fig_height))
    ax.errorbar(
        means,
        y_positions,
        xerr=[lower, upper],
        fmt="o",
        color="#1f77b4",
        ecolor="#3f3f3f",
        elinewidth=1.2,
        capsize=4,
    )
    ax.set_yticks(y_positions)
    ax.set_yticklabels(systems)
    ax.set_xlabel(f"Mean {metric_label} with 95% CI")
    ax.set_title(title, fontsize=16, pad=12)
    ax.set_xlim(-0.03, 1.03)
    ax.grid(axis="x", linestyle=":", linewidth=0.9, alpha=0.75)
    ax.set_axisbelow(True)
    fig.tight_layout()
    fig.savefig(out_png, dpi=200)
    plt.close(fig)


def plot_baseline_delta(
    pivot: Any,
    system_order: list[str],
    metric_label: str,
    baseline: str,
    title: str,
    alpha: float,
    out_png: Path,
) -> None:
    import matplotlib.pyplot as plt

    rows = []
    for system in system_order:
        if system == baseline:
            continue
        diffs = (pivot[system] - pivot[baseline]).tolist()
        mean_diff = statistics.fmean(diffs)
        ci_low, ci_high = confidence_interval(diffs, alpha)
        rows.append((system, mean_diff, ci_low, ci_high))

    if not rows:
        return

    systems = [row[0] for row in rows]
    means = [row[1] for row in rows]
    lower = [mean - row[2] for mean, row in zip(means, rows)]
    upper = [row[3] - mean for mean, row in zip(means, rows)]
    y_positions = list(range(len(systems)))
    max_abs = max(
        0.02,
        *(abs(value) for value in means),
        *(abs(row[2]) for row in rows),
        *(abs(row[3]) for row in rows),
    )

    fig_height = max(4.0, 0.55 * len(systems) + 2.0)
    fig, ax = plt.subplots(figsize=(9.5, fig_height))
    ax.axvline(0.0, color="#3f3f3f", linewidth=1.0)
    ax.errorbar(
        means,
        y_positions,
        xerr=[lower, upper],
        fmt="o",
        color="#2ca02c",
        ecolor="#3f3f3f",
        elinewidth=1.2,
        capsize=4,
    )
    ax.set_yticks(y_positions)
    ax.set_yticklabels(systems)
    ax.set_xlabel(f"Mean {metric_label} difference vs {baseline}")
    ax.set_title(title, fontsize=16, pad=12)
    ax.set_xlim(-max_abs * 1.8, max_abs * 1.8)
    ax.grid(axis="x", linestyle=":", linewidth=0.9, alpha=0.75)
    ax.set_axisbelow(True)
    fig.tight_layout()
    fig.savefig(out_png, dpi=200)
    plt.close(fig)


def p_label(value: float) -> str:
    if math.isnan(value):
        return ""
    if value < 0.001:
        return "<0.001"
    return f"{value:.3f}"


def plot_pvalue_heatmap(
    pairwise_rows: list[dict],
    system_order: list[str],
    metric_label: str,
    title: str,
    out_png: Path,
) -> None:
    import matplotlib.pyplot as plt

    if not pairwise_rows:
        return

    index_by_system = {system: index for index, system in enumerate(system_order)}
    matrix = [[1.0 for _ in system_order] for _ in system_order]
    for row in pairwise_rows:
        i = index_by_system[row["group1"]]
        j = index_by_system[row["group2"]]
        p_value = float(row["p_holm"])
        matrix[i][j] = p_value
        matrix[j][i] = p_value

    fig_size = max(6.5, 0.75 * len(system_order) + 3.0)
    fig, ax = plt.subplots(figsize=(fig_size, fig_size))
    image = ax.imshow(matrix, vmin=0.0, vmax=1.0, cmap="RdYlGn", aspect="equal")
    ax.set_title(title, fontsize=15, pad=12)
    ax.set_xticks(range(len(system_order)))
    ax.set_xticklabels(system_order, rotation=35, ha="right")
    ax.set_yticks(range(len(system_order)))
    ax.set_yticklabels(system_order)

    for row_index, row_values in enumerate(matrix):
        for col_index, value in enumerate(row_values):
            label = "-" if row_index == col_index else p_label(value)
            ax.text(col_index, row_index, label, ha="center", va="center", fontsize=9)

    colorbar = fig.colorbar(image, ax=ax, fraction=0.046, pad=0.04)
    colorbar.set_label("Holm-adjusted Wilcoxon p-value")
    ax.set_xlabel("System")
    ax.set_ylabel("System")
    fig.tight_layout()
    fig.savefig(out_png, dpi=200)
    plt.close(fig)


def plot_overview_heatmap(
    summary_rows: list[dict],
    metric_order: list[str],
    system_order: list[str],
    title: str,
    out_png: Path,
) -> None:
    import matplotlib.pyplot as plt

    if not summary_rows:
        return

    mean_by_metric_system = {
        (row["metric"], row["system"]): float(row["mean"]) for row in summary_rows
    }
    matrix = [
        [mean_by_metric_system[(metric, system)] for system in system_order]
        for metric in metric_order
    ]
    metric_labels = [METRIC_SPECS[metric].label for metric in metric_order]

    fig_width = max(8.0, 1.45 * len(system_order) + 3.0)
    fig_height = max(5.0, 0.45 * len(metric_order) + 2.0)
    fig, ax = plt.subplots(figsize=(fig_width, fig_height))
    image = ax.imshow(matrix, vmin=0.0, vmax=1.0, cmap="viridis", aspect="auto")
    ax.set_title(title, fontsize=16, pad=12)
    ax.set_xticks(range(len(system_order)))
    ax.set_xticklabels(system_order, rotation=30, ha="right")
    ax.set_yticks(range(len(metric_order)))
    ax.set_yticklabels(metric_labels)

    for row_index, row_values in enumerate(matrix):
        for col_index, value in enumerate(row_values):
            text_color = "white" if value < 0.55 else "black"
            ax.text(
                col_index,
                row_index,
                f"{value:.3f}",
                ha="center",
                va="center",
                color=text_color,
                fontsize=9,
            )

    colorbar = fig.colorbar(image, ax=ax, fraction=0.032, pad=0.04)
    colorbar.set_label("Mean score")
    fig.tight_layout()
    fig.savefig(out_png, dpi=200)
    plt.close(fig)


def run_metric(
    input_paths: list[Path],
    metric_name: str,
    metric_dir: Path,
    title_prefix: str,
    baseline: str | None,
    alpha: float,
) -> tuple[list[dict], dict, list[dict], list[str]]:
    metric_label = METRIC_SPECS[metric_name].label
    pivot, system_order = load_metric_frame(input_paths, metric_name)
    baseline_system = baseline or system_order[0]
    if baseline_system not in system_order:
        raise SystemExit(
            f"Baseline '{baseline_system}' is not one of the systems: {system_order}"
        )

    metric_dir.mkdir(parents=True, exist_ok=True)
    summary_rows = summarize_metric(pivot, system_order, metric_name, alpha)
    friedman_row = friedman_test(pivot, system_order, metric_name)
    pairwise_rows = pairwise_wilcoxon(pivot, system_order, metric_name, alpha)

    write_csv(metric_dir / f"{metric_name}_summary.csv", summary_rows)
    write_csv(metric_dir / f"{metric_name}_friedman.csv", [friedman_row])
    write_csv(metric_dir / f"{metric_name}_wilcoxon_holm.csv", pairwise_rows)

    plot_boxplot(
        pivot,
        system_order,
        metric_label,
        f"{title_prefix} - {metric_label} distribution",
        metric_dir / f"{metric_name}_boxplot.png",
    )
    plot_mean_ci(
        summary_rows,
        metric_label,
        f"{title_prefix} - mean {metric_label}",
        metric_dir / f"{metric_name}_mean_ci.png",
    )
    plot_baseline_delta(
        pivot,
        system_order,
        metric_label,
        baseline_system,
        f"{title_prefix} - {metric_label} delta vs baseline",
        alpha,
        metric_dir / f"{metric_name}_baseline_delta.png",
    )
    plot_pvalue_heatmap(
        pairwise_rows,
        system_order,
        metric_label,
        f"{title_prefix} - {metric_label} pairwise significance",
        metric_dir / f"{metric_name}_holm_pvalues.png",
    )

    return summary_rows, friedman_row, pairwise_rows, system_order


def main() -> None:
    args = parse_args()

    require_dependency("pandas")
    require_dependency("matplotlib")
    require_dependency("scipy")

    input_paths = [Path(path) for path in args.inputs]
    metrics = selected_metrics(args)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    all_summary_rows: list[dict] = []
    all_friedman_rows: list[dict] = []
    all_pairwise_rows: list[dict] = []
    overview_system_order: list[str] | None = None

    for metric_name in metrics:
        metric_dir = outdir / metric_name
        summary_rows, friedman_row, pairwise_rows, system_order = run_metric(
            input_paths=input_paths,
            metric_name=metric_name,
            metric_dir=metric_dir,
            title_prefix=args.title,
            baseline=args.baseline,
            alpha=args.alpha,
        )
        all_summary_rows.extend(summary_rows)
        all_friedman_rows.append(friedman_row)
        all_pairwise_rows.extend(pairwise_rows)
        if overview_system_order is None:
            overview_system_order = system_order

    write_csv(outdir / "summary_all_metrics.csv", all_summary_rows)
    write_csv(outdir / "friedman_all_metrics.csv", all_friedman_rows)
    write_csv(outdir / "wilcoxon_holm_all_metrics.csv", all_pairwise_rows)

    if overview_system_order is not None:
        plot_overview_heatmap(
            all_summary_rows,
            metrics,
            overview_system_order,
            f"{args.title} - mean metric overview",
            outdir / "mean_metric_overview.png",
        )

    print(f"Saved comparison plots and CSV files under: {outdir}")


if __name__ == "__main__":
    main()
